In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1,2],[3,4],[5,6]]

In [ ]:
data

[[1, 2], [3, 4], [5, 6]]

In [ ]:
type(data)

list

In [ ]:
np_data = np.array(data)

In [ ]:
np_data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
torch_data = torch.tensor(data)

In [ ]:
torch_data

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor = torch.from_numpy(np_data)

In [ ]:
tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")
  print(f"stored in : {tensor.device}")
else:
  print("oops!")

oops!


In [ ]:
tensor * tensor

tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]])

In [ ]:
tensor **28

tensor([[                   1,            268435456],
        [      22876792454961,    72057594037927936],
        [  359414837200037393, -1823562080465190912]])

In [ ]:
tensor.mul(3)

tensor([[ 3,  6],
        [ 9, 12],
        [15, 18]])

In [ ]:
torch.cat([tensor, tensor, tensor], dim=1)

tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [5, 6, 5, 6, 5, 6]])